app:
  host: "0.0.0.0"
  port: 8000

db:
  host: "localhost"
  port: 5432
  name: "postgres"
  user: "postgres"
  password: "postgres"
  pool_size: 15

worker:
  interval: 15

rabbitmq:
  url: amqp://guest:guest@localhost:5672/
  logs_queue: logs.process
